export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';


export const FETCH_REQUEST = 'FETCH_REQUEST';

export const GET_TEMPLATES_REQUEST = 'GET_TEMPLATES_REQUEST';
export const ADD_TEMPLATES_SUCCESS = 'ADD_TEMPLATES_SUCCESS';

export const IS_ACTIVE_FIRST_TEMPLATE = 'IS_ACTIVE_FIRST_TEMPLATE';
export const IS_ACTIVE_SECOND_TEMPLATE = 'IS_ACTIVE_SECOND_TEMPLATE';
export const IS_ACTIVE_ALL_TEMPLATE = 'IS_ACTIVE_ALL_TEMPLATE';
